const arts = [
  {
    directory: "reclaimed",
    title: "Reclaimed",
    preview: "stbw.png",
    tags: ["art", "sculpture"],
    hasDetail: true,
    date: new Date("01/06/2020"),
    description: "Group show featuring recycled materials",
  },
  {
    directory: "jacmb",
    title: "Jacmb",
    preview: "maki.jpg",
    tags: ["music"],
    hasDetail: true,
    date: new Date("10/01/2007"),
    description: "Solo music",
  },
  {
    directory: "hyperlasso",
    title: "Hyper Lasso",
    preview: "preview.gif",
    tags: ["game", "mobile"],
    hasDetail: true,
    date: new Date("05/01/2021"),
    description: "Chaotic space arcade game for iOS",
  },
  {
    directory: "aristid",
    title: "Aristid",
    preview: "aristid.jpg",
    tags: ["music"],
    hasDetail: true,
    date: new Date("10/01/2016"),
    description: "Fractal music slicing",
  },
  {
    directory: "brandoSkirts",
    title: "Brando Skirts",
    preview: "brando.png",
    tags: ["music"],
    hasDetail: true,
    date: new Date("10/01/2005"),
    description: "Early '00s indie noise pop",
  },
  {
    directory: "monsterPlotter",
    title: "Monster Plotter",
    preview: "preview2.gif",
    tags: ["hardware", "art"],
    hasDetail: true,
    date: new Date("4/01/2020"),
    description: "Large DIY art robot",
  },
  {
    directory: "fleas",
    title: "Fleas",
    preview: "fleas.png",
    tags: ["web", "game", "software"],
    hasDetail: true,
    date: new Date("10/01/2011"),
    description: "Simple game about a bug anxiety",
  },
  {
    directory: "graphix",
    title: "Graphix",
    preview: "preview.png",
    tags: ["art", "software"],
    hasDetail: true,
    date: new Date("10/01/2014"),
    description: "Using code to make pretty things",
  },
  {
    directory: "metaflux",
    title: "Metaflux",
    preview: "output.gif",
    tags: ["art"],
    hasDetail: true,
    date: new Date("10/03/2018"),
    description: "Group show about tech-enabled art process",
  },
  {
    directory: "microscope",
    title: "The Microscope Taught Me the Universe is Infinite in Both Directions",
    preview: "movlow.gif",
    tags: ["music", "art", "video"],
    hasDetail: true,
    date: new Date("04/09/2015"),
    description: "Live audio/visual performance",
  },
  {
    directory: "pendrillum",
    title: "Pendrillum",
    preview: "drill.gif",
    tags: ["web", "hardware"],
    hasDetail: true,
    date: new Date("11/01/2017"),
    description: "This is not a drill",
  },
  {
    directory: "pixel",
    title: "Pixel Pattern Maker",
    preview: "pixel.png",
    tags: ["web", "software"],
    hasDetail: true,
    date: new Date("10/01/2013"),
    description: "Simple pattern drawing app",
  },
  {
    directory: "plotter",
    title: "Pantograph Plotter",
    preview: "plotter.jpg",
    tags: ["hardware", "art"],
    hasDetail: true,
    date: new Date("06/01/2017"),
    description: "Modified art machine",
  },
  {
    directory: "talka",
    title: "Talka",
    preview: "ss.jpg",
    tags: ["software", "music", "mobile"],
    hasDetail: true,
    date: new Date("10/01/2015"),
    description: "Text-to-speech music iOS app",
  },
  {
    directory: "tens",
    title: "Tens",
    preview: "movlow.gif",
    tags: ["video", "music"],
    hasDetail: true,
    date: new Date("01/02/2020"),
    description: "Synchronized music video",
  },
  {
    directory: "vectorray",
    title: "Vectorray",
    preview: "vectorray.png",
    tags: ["web", "software", "art"],
    hasDetail: true,
    date: new Date("01/01/2017"),
    description: "Recursive drawing with code",
  },
  {
    directory: "video",
    title: "Videos",
    preview: "vid.gif",
    tags: ["video", "music"],
    hasDetail: true,
    date: new Date("01/01/2017"),
    description: "Selected video art",
  },
];

// const details = {
//   reclaimed: (_) =>  html`<h4>hi</h4>`
//   },
// };
