const works = [
  {
    directory: "drivers-coop",
    title: "The Drivers Co-op",
    externalLink: "https://drivers.coop",
    preview: "preview.png",
    tags: ["mobile", "design", "research"],
    date: new Date("6/1/2021"),
    hasDetail: true,
    description: "Head of Product at the 100% worker-owned rideshare cooperative",
  },
  {
    directory: "promise-web",
    title: "Promise Case Manager",
    preview: "preview.png",
    tags: ["web", "design", "research"],
    date: new Date("1/1/2018"),
    hasDetail: false,
    description: "Drop-in pre-trial support program to keep people out of jail",
  },
  {
    directory: "promise-mobile",
    title: "Promise Client App",
    preview: "preview.png",
    tags: ["mobile", "design", "research"],
    date: new Date("1/1/2018"),
    hasDetail: false,
    description:
      "Better communication and information sharing for people released from jail to a supportive pre-trial program",
  },
  {
    directory: "uberpool",
    title: "Uber Pool",
    preview: "preview.png",
    tags: ["design", "mobile"],
    date: new Date("6/1/2014"),
    hasDetail: false,
    description: "Co-led design for launch of the carpooling ride option",
  },
  {
    directory: "synoptic",
    title: "Uber Synoptic",
    preview: "preview.png",
    tags: ["web", "design", "product"],
    date: new Date("11/1/2016"),
    hasDetail: false,
    description: "Auto-generated alerting and monitoring dashboard system",
  },
  {
    directory: "messaging",
    title: "Uber Mobile Messaging",
    preview: "preview.png",
    tags: ["design", "mobile"],
    date: new Date("2/20/2013"),
    hasDetail: false,
    description:
      "Rider app feature used by city teams to communicate with riders about product launches, fare changes, promotions, service disruptions, etc",
  },
  {
    directory: "uber-data-vis",
    title: "Uber Data Vis System",
    preview: "preview.png",
    tags: ["hardware", "art"],
    date: new Date("4/01/2015"),
    hasDetail: false,
    description:
      "Contributed to design system and tools for internal & external data visualization",
  },
  {
    directory: "uber-sound",
    title: "Uber Sound Design",
    preview: "preview.png",
    tags: ["sound"],
    date: new Date("2/01/2016"),
    hasDetail: false,
    description: "Sound effects for driver app and self-driving car operators",
  },
  {
    directory: "uber-branding",
    title: "Uber Branding",
    preview: "preview.png",
    tags: ["design", "software"],
    date: new Date("10/01/2014"),
    hasDetail: false,
    description: "Generative design system for a big Uber employee convention",
  },
  {
    directory: "uber-summary",
    title: "Uber Summary (v1-3)",
    preview: "preview.png",
    tags: ["web", "design"],
    date: new Date("10/01/2013"),
    hasDetail: false,
    description: "Performance dashboard used by all operations employees and executives",
  },
  {
    directory: "uber-jaeger",
    title: "Uber Jaeger",
    preview: "preview.png",
    tags: ["web", "design"],
    date: new Date("1/03/2017"),
    hasDetail: false,
    description: "Open source infrastructure call tracing tool",
  },
  {
    directory: "uber-heaven",
    title: "Uber Heaven Charts",
    preview: "preview.png",
    tags: ["art", "video"],
    date: new Date("04/09/2014"),
    hasDetail: false,
    description: "Real-time charts and map viz tool for city operations",
  },
  {
    directory: "bamboo",
    title: "BambooAI",
    preview: "preview.png",
    tags: ["design", "mobile"],
    date: new Date("6/1/2020"),
    hasDetail: false,
    description: "Facebook ad automated management",
  },
  {
    directory: "explor",
    title: "Explor (née Appsaurus)",
    preview: "preview.png",
    tags: ["web", "hardware"],
    date: new Date("5/01/2011"),
    hasDetail: false,
    description: "iPhone app for discovering iPhone apps",
  },
];
